name: Mirroring

on: [push, delete]

jobs:
  to_bitbucket:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:          # <-- Enter the SSH URL to mirror the Github repo to.
          git@bitbucket.org:OmiyaGames/template-unity-package.git
        ssh_private_key:          # <-- Add a secret in Github with the name, SSH_PRIVATE_KEY.
          ${{ secrets.SSH_PRIVATE_KEY }}
